spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  profiles: dev
  #  配置应用名
  application:
    name: springcloud-demo-provider-dept
  #    配置数据库连接池相关属性
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: mysql
      url: jdbc:mysql://127.0.0.1:3306/clouddb03?serverTimezone=GMT%2B8
      driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  #  开启类别名
  type-aliases-package: cn.ly.springcloud.demo.api.entities
  #  指定mapper文件所在位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #    开启驼峰命名
    map-underscore-to-camel-case: true
    #    开启二级缓存
    cache-enabled: true

# eureka 相关配置
eureka:
  client:
    #   启用健康检查，以/health节点下的状态来判断服务实例处于何种状态
    healthcheck:
      enabled: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    #   修改服务名称
    instanceId: provider-dept8001
    #   访问路径可以显示ip地址
    prefer-ip-address: true

---
server:
  port: 8001
spring:
  profiles: test
  #  配置应用名
  application:
    name: springcloud-demo-provider-dept
  #    配置数据库连接池相关属性
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: mysql
      url: jdbc:mysql://127.0.0.1:3306/clouddb02?serverTimezone=GMT%2B8
      driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  #  开启类别名
  type-aliases-package: cn.ly.springcloud.demo.api.entities
  #  指定mapper文件所在位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #    开启驼峰命名
    map-underscore-to-camel-case: true
    #    开启二级缓存
    cache-enabled: true

# eureka 相关配置
eureka:
  client:
    #   启用健康检查，以/health节点下的状态来判断服务实例处于何种状态
    healthcheck:
      enabled: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    #   修改服务名称
    instanceId: provider-dept8001
    #   访问路径可以显示ip地址
    prefer-ip-address: true

