spring:
  profiles:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  #  配置应用名
  application:
    name: springcloud-demo-config-client
eureka:
  client:
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  #  配置应用名
  application:
    name: springcloud-demo-config-client
eureka:
  client:
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka-test.com:7001/eureka/